<?php					
include "menux.php";					
$heading="Articles( Articulos)";
$subheading="The Spanish Lo (el articulo lo)";
$point1="Lo is never used with a noun. Lo can be used with a masculine singular adjective or past participle (the -ado and -ido forms of regular verbs) to form a noun. Lo cannot be used with a noun, it is used with a masculine adjective (singular) or in the noun form of the -ado and ido forms of regular verbs (which are also past participles) ";
$english1="that is why, hence";
$spanish1="por lo cual";
$english1a="She was sick, that is why she could not come.";
$spanish1a="Ella estaba enferma, por lo cual no pudo venir.";
$english1b="at least";
$spanish1b="por lo menos";
$english1c="At least you can have tea.";
$spanish1c="Por lo menos, puedes tomar té";
$english1d="generally";
$spanish1d="por lo general";
$english1e="Generally I do not travel much";
$spanish1e="Por lo general no suelo viajar mucho.";
$point2="lo is used with que (translates to - what).";
$english2="I don't understand what you are saying.";
$spanish2="No entiendo lo que dices.";
$english2a="What attracts me most is his voice.";
$spanish2a="Lo que más me atrae es su voz.";
$english2b="";
$spanish2b="";
$english2c="";
$spanish2c="";
$english2d="";
$spanish2d="";
$english2e="";
$spanish2e="";
$point3="LO can be used with de followed by a noun phrase to refer back to a particular matter known to the speaker and listener both.";
$english3="About your suggestion to travel in winter, I dont like it at all.";
$spanish3="Lo de tu sugerencia de viajar en invierno no me gusta nada.";
$english3a="It would be best to forget what happened yesterday.";
$spanish3a="Lo de ayer es mejor que lo olvides.";
$english3b="";
$spanish3b="";
$english3c="";
$spanish3c="";
$english3d="";
$spanish3d="";
$english3e="";
$spanish3e="";
$point4="lo can be used with an adjective followed by que to describe its extent (lo+adjective+que). It should be noted that adjective must match the noun it describes. (for example, if the noun is chica then the adjective will be buena and not bueno. If the noun is chico then the adjective would be bueno.)";
$english4="We didn’t know how bad the situation was.";
$spanish4="No sabíamos lo malo que era la situación.";
$english4a="You can’t measure how deep the ocean is.";
$spanish4a="No puedes medir lo profundo que es el oceano.";
$english4b="";
$spanish4b="";
$english4c="";
$spanish4c="";
$english4d="";
$spanish4d="";
$english4e="";
$spanish4e="";
$point5="Lo can also be used to with an adverb  (lo+adverb+que.)";
$english5="I saw how much you like to dance.";
$spanish5="Ví lo mucho que te gusta bailar.";
$english5a="";
$spanish5a="";
$english5b="";
$spanish5b="";
$english5c="";
$spanish5c="";
$english5d="";
$spanish5d="";
$english5e="";
$spanish5e="";
$explain="in Spanish is";




?>